name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    name: Deploy to NPM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: node_modules cache
        uses: actions/cache@v4
        id: node_modules-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: pnpm cache
        if: steps.node_modules-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        id: pnpm-store
        with:
          path: ~/.pnpm-store/v4
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        
